package:
  authors:
    - Tatsuya Koishi
  description: 「ドラゴンクエストダイの大冒険」に関する、各種記念日をtomato-shriekerから扱えるようにするユーティリティ。
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/dqdai-anniv
  version: 1.0.6
calendar:
  - name: character
    url: https://mstdn.delmulin.com/api/character/v1/detail.json
  - name: anniversary
    url: https://mstdn.delmulin.com/api/anniversary/v1/common.json
http:
  retry:
    limit: 3
    seconds: 1
